import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright-core';
import { ElectronBridge } from '../dist/bridge.js';
import { importCharacter } from './helpers/characters.mjs';

let display, browser;
let bridge = new ElectronBridge();
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const dataDir = await mkdtemp(join(tmpdir(), 'dsh-pet-test-'));
process.env.DSH_PET_TEST_DATA_DIR = dataDir;
process.env.XDG_CONFIG_HOME = dataDir;
process.env.XDG_CACHE_HOME = dataDir;
try {
  if (process.platform === 'linux' && !process.env.DISPLAY) {
    const number = 100 + process.pid % 1000;
    const command = process.env.XVFB_PATH ?? 'Xvfb';
    display = spawn(command, [`:${number}`, '-screen', '0', '1200x800x24', '-nolisten', 'tcp'], { stdio: ['ignore', 'ignore', 'pipe'] });
    let displayError;
    display.on('error', error => { displayError = error; });
    for (let attempt = 0; attempt < 30 && !existsSync(`/tmp/.X11-unix/X${number}`); attempt++) {
      if (displayError) throw displayError;
      if (display.exitCode !== null) throw new Error('Xvfb exited before becoming ready');
      await pause(100);
    }
    if (!existsSync(`/tmp/.X11-unix/X${number}`)) throw new Error('Xvfb did not create its display socket');
    process.env.DISPLAY = `:${number}`;
  }
  const portServer = createServer(); portServer.listen(0, '127.0.0.1'); await once(portServer, 'listening');
  const port = portServer.address().port; await new Promise(resolve => portServer.close(resolve));
  process.env.DSH_PET_TEST_DEBUG_PORT = String(port);
  process.env.DSH_PET_TEST_NO_SANDBOX = '1';
  const actions = []; bridge.onAction(action => actions.push(action));
  const failures = []; bridge.on('failure', error => failures.push(error.message));
  const snapshot = { mood: 'thinking', text: '真实 IPC 桌面测试', sessionId: 'native-test', sessions: [{ id: 'native-test', label: '桌面测试会话', mood: 'thinking', text: '', reply: '' }] };
  bridge.update(snapshot);
  await bridge.start({ size: 150, roam: false, notifications: false, bubbleDurationMs: 12000 });
  browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
  let page = browser.contexts()[0].pages()[0];
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '真实 IPC 桌面测试');
  assert.equal(await page.locator('#demo').isVisible(), false, 'native window does not masquerade as a browser demo');
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined', 'renderer has no Node access');
  assert.equal(await page.locator('#pet').getAttribute('data-mood'), 'thinking');
  await page.locator('#pet').dblclick(); await page.locator('#message').fill('通过桌宠发送'); await page.locator('#send').click();
  for (let n = 0; n < 30 && actions.length === 0; n++) await pause(50);
  assert.deepEqual(actions[0], { type: 'chat', text: '通过桌宠发送', sessionId: 'native-test' });
  bridge.update({ ...snapshot, mood: 'happy', text: '宿主回复已到达。' });
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '宿主回复已到达。');
  bridge.notify({ title: '桌面测试 · 已完成', body: '真实窗口与宿主 IPC 验证通过。', sessionId: 'native-test' });
  await page.waitForSelector('#toast:not([hidden])');
  assert.equal(await page.locator('#toast-title').innerText(), '桌面测试 · 已完成');
  await page.locator('#toast').click();
  for (let n = 0; n < 30 && actions.length < 2; n++) await pause(50);
  assert.deepEqual(actions[1], { type: 'open-session', sessionId: 'native-test' });
  bridge.update({ ...snapshot, mood: 'idle', text: '准备好了，随时叫我。', revision: 2, sessions: [...snapshot.sessions, { id: 'second-test', label: '另一会话', mood: 'working', text: '正在运行命令', reply: '', revision: 1 }] });
  await page.waitForFunction(() => document.getElementById('pet').dataset.mood === 'idle');
  await page.locator('#open-sessions').click();
  assert.match(await page.locator('.conversation-intro').innerText(), /选一段，我就转过去陪着/);
  await page.locator('#conversation-list [data-session-id="second-test"]').click();
  assert.match(await page.locator('#bubble-text').innerText(), /好，我来听.*另一会话.*正在忙/);
  for (let n = 0; n < 30 && actions.length < 3; n++) await pause(50);
  assert.deepEqual(actions[2], { type: 'select', sessionId: 'second-test' });
  await page.keyboard.press('Escape');
  await page.waitForSelector('#pet[data-character=deepseek-whale]');
  await page.locator('#pet').click({ button: 'right' }); await page.locator('#open-characters').click();
  await importCharacter(page, 'paper-star.dshpet');
  await page.waitForFunction(() => document.getElementById('character-select').value === 'paper-star' && !document.getElementById('character-use').disabled);
  await page.locator('#character-use').click(); await page.waitForSelector('#pet[data-character=paper-star]');
  assert.match(await page.locator('#character-credit').innerText(), /MIT/);
  await page.locator('#character-select').selectOption('deepseek-whale');
  await page.waitForFunction(() => document.getElementById('character-select').value === 'deepseek-whale' && !document.getElementById('character-use').disabled);
  await page.locator('#character-use').click(); await page.waitForSelector('#pet[data-character=deepseek-whale]');
  assert.match(await page.locator('#character-credit').innerText(), /Pal-AI-Lab.*ZipZipPipe/);
  assert.equal(actions.filter(action => action.type === 'chat').length, 1, 'character import and session navigation do not send extra model messages');
  await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: 'artifacts/native-pet.png' });
  await bridge.dispose();
  await browser.close(); browser = undefined;
  bridge = new ElectronBridge(); bridge.on('failure', error => failures.push(error.message)); bridge.update(snapshot);
  await bridge.start({ size: 150, roam: false, notifications: false, bubbleDurationMs: 12000 });
  browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`); page = browser.contexts()[0].pages()[0];
  await page.waitForSelector('#pet[data-character=deepseek-whale]');
  await page.locator('#pet').click({ button: 'right' }); await page.locator('#open-characters').click();
  await page.waitForFunction(() => document.getElementById('character-remove').disabled);
  assert.equal(await page.locator('#character-select option[value=paper-star]').count(), 1);
  await bridge.dispose();
  assert.deepEqual(failures, []);
  console.log('Native smoke passed: Electron ready handshake, isolated renderer, two-way chat IPC, host reply, notification, and clean shutdown.');
  console.log('Native character smoke passed: import, selection, disk persistence across process restart, and removal.');
} finally {
  await bridge.dispose();
  if (browser) await browser.close();
  if (display?.exitCode === null) { display.kill(); await once(display, 'exit'); }
  await rm(dataDir, { recursive: true, force: true });
}
