import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { chromium } from 'playwright-core';
import { ElectronBridge } from '../dist/bridge.js';
import { importCharacter } from './helpers/characters.mjs';
import { petClick } from './helpers/native-pointer.mjs';
import { unzipSync } from 'fflate';

let display, browser;
let bridge = new ElectronBridge();
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const dataDir = await mkdtemp(join(tmpdir(), 'dsh-pet-test-'));
process.env.DSH_PET_TEST_DATA_DIR = dataDir;
process.env.XDG_CONFIG_HOME = dataDir;
process.env.XDG_CACHE_HOME = dataDir;
try {
  if (process.platform === 'linux' && !process.env.DISPLAY) {
    const number = 100 + process.pid % 1000;
    const command = process.env.XVFB_PATH ?? 'Xvfb';
    display = spawn(command, [`:${number}`, '-screen', '0', '1200x800x24', '-nolisten', 'tcp'], { stdio: ['ignore', 'ignore', 'pipe'] });
    let displayError;
    display.on('error', error => { displayError = error; });
    for (let attempt = 0; attempt < 30 && !existsSync(`/tmp/.X11-unix/X${number}`); attempt++) {
      if (displayError) throw displayError;
      if (display.exitCode !== null) throw new Error('Xvfb exited before becoming ready');
      await pause(100);
    }
    if (!existsSync(`/tmp/.X11-unix/X${number}`)) throw new Error('Xvfb did not create its display socket');
    process.env.DISPLAY = `:${number}`;
  }
  const portServer = createServer(); portServer.listen(0, '127.0.0.1'); await once(portServer, 'listening');
  const port = portServer.address().port; await new Promise(resolve => portServer.close(resolve));
  process.env.DSH_PET_TEST_DEBUG_PORT = String(port);
  process.env.DSH_PET_TEST_NO_SANDBOX = '1';
  const actions = []; bridge.onAction(action => actions.push(action));
  const trayStates = []; bridge.on('tray-state', state => trayStates.push(state));
  const waitTray = async check => { for (let n = 0; n < 100; n++) { if (check(trayStates.at(-1))) return; await pause(50); } assert.fail('native tray did not synchronize'); };
  const failures = []; bridge.on('failure', error => failures.push(error.message));
  const snapshot = { mood: 'thinking', text: '真实 IPC 桌面测试', sessionId: 'native-test', sessions: [{ id: 'native-test', label: '桌面测试会话', mood: 'thinking', text: '', reply: '' }] };
  bridge.update(snapshot);
  await bridge.start({ size: 150, roam: false, notifications: true, bubbleDurationMs: 12000 });
  browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
  let page = browser.contexts()[0].pages()[0];
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '真实 IPC 桌面测试');
  assert.equal(await page.locator('#demo').isVisible(), false, 'native window does not masquerade as a browser demo');
  assert.equal(await page.evaluate(() => typeof window.require), 'undefined', 'renderer has no Node access');
  assert.equal(await page.locator('#pet').getAttribute('data-mood'), 'thinking');
  await waitTray(state => state?.mood === 'thinking' && state.sessionId === 'native-test');
  await page.waitForSelector('#pet[data-mode]');
  const sandbox = await page.locator('#body-layer iframe').contentFrame().locator('body').evaluate(() => {
    let blocked = false; try { parent.document.body; } catch { blocked = true; }
    return { blocked, bridge: typeof window.dshPetBridge, node: typeof window.require, webgl: !!document.querySelector('canvas').getContext('webgl2') };
  });
  assert.deepEqual(sandbox, { blocked: true, bridge: 'undefined', node: 'undefined', webgl: true });
  const sourceResponse = await fetch(new URL('./source', page.url()));
  assert.equal(sourceResponse.status, 200);
  const source = unzipSync(new Uint8Array(await sourceResponse.arrayBuffer()));
  assert.ok(source['src/figure-server.ts'] && source['npm-shrinkwrap.json']);
  await petClick(page, {}, true); await page.locator('#message').fill('通过桌宠发送'); await page.locator('#send').click();
  for (let n = 0; n < 30 && actions.length === 0; n++) await pause(50);
  assert.deepEqual(actions[0], { type: 'chat', text: '通过桌宠发送', sessionId: 'native-test' });
  bridge.update({ ...snapshot, mood: 'happy', text: '宿主回复已到达。' });
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '宿主回复已到达。');
  bridge.notify({ title: '桌面测试 · 已完成', body: '真实窗口与宿主 IPC 验证通过。', sessionId: 'native-test' });
  await page.waitForSelector('#toast:not([hidden])');
  assert.equal(await page.locator('#toast-title').innerText(), '桌面测试 · 已完成');
  await page.locator('#toast').click();
  for (let n = 0; n < 30 && actions.length < 2; n++) await pause(50);
  assert.deepEqual(actions[1], { type: 'open-session', sessionId: 'native-test' });
  bridge.update({ ...snapshot, mood: 'idle', text: '准备好了，随时叫我。', revision: 2, sessions: [...snapshot.sessions, { id: 'second-test', label: '另一会话', mood: 'working', text: '正在运行命令', reply: '', revision: 1 }] });
  await page.waitForFunction(() => document.getElementById('pet').dataset.mood === 'idle');
  await petClick(page, {}, true); await page.locator('#chat-current').click();
  assert.match(await page.locator('.conversation-intro').innerText(), /选一段，我就转过去陪着/);
  await page.locator('#conversation-list [data-session-id="second-test"]').click();
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent.includes('正在忙'));
  assert.match(await page.locator('#bubble-text').innerText(), /好，我来听.*另一会话.*正在忙/);
  for (let n = 0; n < 30 && actions.length < 3; n++) await pause(50);
  assert.deepEqual(actions[2], { type: 'select', sessionId: 'second-test' });
  await page.keyboard.press('Escape');
  await page.waitForSelector('#pet[data-character=whale]');
  await petClick(page, { button: 'right' }); await page.locator('#open-characters').click();
  await importCharacter(page, 'paper-star.zip');
  await page.waitForFunction(() => document.getElementById('character-select').value === 'paper-star' && !document.getElementById('character-use').disabled);
  await page.locator('#character-use').click(); await page.waitForSelector('#pet[data-character=paper-star]');
  assert.match(await page.locator('#character-credit').innerText(), /AGPL/);
  await page.locator('#character-select').selectOption('whale');
  await page.waitForFunction(() => document.getElementById('character-select').value === 'whale' && !document.getElementById('character-use').disabled);
  await page.locator('#character-scheme').selectOption('claude');
  await page.waitForFunction(() => !document.getElementById('character-use').disabled);
  await page.locator('#character-use').click(); await page.waitForSelector('#pet[data-character=whale][data-scheme=claude]');
  assert.match(await page.locator('#character-credit').innerText(), /Pal-AI-Lab.*ZipZipPipe/);
  await waitTray(state => state?.scheme === 'claude' && state.characterId === 'whale');
  assert.equal(actions.filter(action => action.type === 'chat').length, 1, 'character import and session navigation do not send extra model messages');
  await mkdir('artifacts', { recursive: true }); await page.screenshot({ path: 'artifacts/native-pet.png' });
  await page.locator('#character-select').selectOption('paper-star');
  await page.waitForFunction(() => !document.getElementById('character-use').disabled);
  await page.locator('#character-scheme').selectOption('night');
  await page.waitForFunction(() => !document.getElementById('character-use').disabled);
  await page.locator('#character-use').click(); await page.waitForSelector('#pet[data-character=paper-star][data-scheme=night]');
  await page.locator('#characters-close').click();
  bridge.update({ ...snapshot, mood: 'idle', active: false, text: '现在可以休息。', revision: 3 });
  await page.waitForSelector('#pet[data-mood=idle]');
  await petClick(page, { button: 'right' }); await page.locator('#toggle-sleep').click();
  await page.waitForSelector('#pet[data-mode=sleep]');
  await waitTray(state => state?.sleeping === true && state.scheme === 'night');
  bridge.update({ ...snapshot, active: true, revision: 4 });
  await page.waitForSelector('#pet[data-mood=thinking]');
  await page.waitForFunction(() => document.getElementById('pet').dataset.mode !== 'sleep');
  await waitTray(state => state?.mood === 'thinking' && !state.sleeping);
  const live = { ...snapshot, active: true, mood: 'talking', speechId: 'native-stream', streaming: true, revision: 5, text: '实时' };
  bridge.update(live); await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '实时');
  bridge.update({ ...live, text: '实时回复', revision: 6 });
  assert.match(await page.locator('#bubble-text').innerText(), /^实时/, 'appending a native live delta preserves the visible prefix');
  await page.waitForFunction(() => document.getElementById('bubble-text').textContent === '实时回复');
  await waitTray(state => state?.mood === 'talking' && state.title === '回复');
  await page.locator('#dismiss').click();
  bridge.update({ ...live, text: '实时回复继续', revision: 7 });
  await pause(150);
  assert.equal(await page.locator('#bubble').isVisible(), false, 'dismissed live speech stays closed as more deltas arrive');
  bridge.configure({ size: 150, roam: false, notifications: false, bubbleDurationMs: 12000 });
  await waitTray(state => state?.roam === false && state.notifications === false);
  bridge.control('hide'); await waitTray(state => state?.visible === false);
  bridge.control('show'); await waitTray(state => state?.visible === true);
  await bridge.dispose();
  await browser.close(); browser = undefined;
  bridge = new ElectronBridge(); bridge.on('failure', error => failures.push(error.message)); bridge.update(snapshot);
  await bridge.start({ size: 150, roam: false, notifications: false, bubbleDurationMs: 12000 });
  browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`); page = browser.contexts()[0].pages()[0];
  await page.waitForSelector('#pet[data-character=paper-star][data-scheme=night]');
  await petClick(page, { button: 'right' }); await page.locator('#open-characters').click();
  await page.waitForFunction(() => !document.getElementById('character-remove').disabled);
  assert.equal(await page.locator('#character-select option[value=paper-star]').count(), 1);
  await page.locator('#character-remove').click(); await page.waitForSelector('#pet[data-character=whale]');
  await page.waitForFunction(() => document.getElementById('character-status').textContent.includes('已删除本地角色包'));
  await page.waitForFunction(() => document.getElementById('character-remove').disabled);
  assert.equal(await page.locator('#character-select option[value=paper-star]').count(), 0);
  await bridge.dispose();
  assert.deepEqual(failures, []);
  console.log('Native smoke passed: Electron ready handshake, isolated renderer, two-way chat IPC, host reply, notification, and clean shutdown.');
  console.log('Native character smoke passed: import, selection, disk persistence across process restart, and removal.');
} finally {
  await bridge.dispose();
  if (browser) await browser.close();
  if (display?.exitCode === null) { display.kill(); await once(display, 'exit'); }
  await rm(dataDir, { recursive: true, force: true });
}
