import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const entries = execFileSync('tar', ['-tzf', `${pkg.name}-${pkg.version}.tgz`], { encoding: 'utf8' }).trim().split('\n');
assert.equal(pkg.license, 'AGPL-3.0-or-later');
assert.equal(pkg.exports['./client'], './dist/client.js');
assert.equal(pkg.dsh.client.platform, 'web');
for (const required of ['dist/client.js', 'dist/index.js', 'dist/character-store.cjs', 'dist/figure-server.cjs', 'cordis.patch.yml', 'desktop/main.cjs', 'desktop/tray-state.cjs', 'desktop/preload.cjs', 'web/index.html', 'web/pet.js', 'web/speech.js', 'web/session-ui.js', 'web/upstream/kit/rig.js', 'web/upstream/kit/body.js', 'web/upstream/figure-frame.html', 'web/upstream/body-host.js', 'web/upstream/whale/figure.json', 'web/upstream/whale/model.json', 'web/upstream/whale/tex/face.png', 'web/upstream/UPSTREAM.md', 'web/upstream/THIRD_PARTY_NOTICES.md', 'src/figure-server.ts', 'src/upstream/packs.ts', 'scripts/build.mjs', 'npm-shrinkwrap.json', 'tsconfig.json', 'tsconfig.client.json', 'docs/characters.md', 'examples/star/figure.json', 'examples/star/figure.js', 'tests/figures.test.ts', 'THIRD_PARTY_NOTICES.md', 'LICENSE', 'LICENSE-MIT', 'README.md']) assert.ok(entries.includes(`package/${required}`), `missing ${required}`);
assert.ok(!entries.some(path => path.includes('node_modules/') || path.includes('.cache/')));
assert.ok(!entries.some(path => /character-runtime|character.schema|\/animation\.|\/character-pack\.|\/web\/characters\//.test(path)), 'old engine and format must not be packaged');
console.log(`Package verified: ${entries.length} files, upstream runtime, native host and corresponding source included.`);
