import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const entries = execFileSync('tar', ['-tzf', `${pkg.name}-${pkg.version}.tgz`], { encoding: 'utf8' }).trim().split('\n');
assert.ok(entries.includes('package/dist/client.js'), 'missing the DSH settings client bundle');
assert.equal(pkg.exports['./client'], './dist/client.js');
assert.equal(pkg.dsh.client.platform, 'web');
for (const required of ['package/dist/index.js', 'package/dist/character-store.cjs', 'package/cordis.patch.yml', 'package/desktop/main.cjs', 'package/desktop/preload.cjs', 'package/web/index.html', 'package/web/pet.js', 'package/web/style.css', 'package/web/character-runtime.js', 'package/web/characters/deepseek-whale/assets/head.png', 'package/web/characters/deepseek-whale/manifest.js', 'package/web/characters/deepseek-whale/LICENSE', 'package/docs/characters.md', 'package/docs/character.schema.json', 'package/examples/star/character.json', 'package/THIRD_PARTY_NOTICES.md', 'package/LICENSE', 'package/README.md']) assert.ok(entries.includes(required), `missing ${required}`);
assert.ok(!entries.some(path => path.includes('node_modules/') || path.includes('tests/') || path.includes('.cache/')));
assert.ok(!entries.some(path => path.includes('/characters/whale/')), 'legacy small-whale artwork must not be packaged');
console.log(`Package verified: ${entries.length} files, native window and renderer included.`);
